#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1530030278                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get to know your infinity bottle.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nick Smart                          
your_link                                 :                    
your_city                                 :                                
email_address                             : codelab703@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : nicholassmart
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Unlimited Bottles
    description                           : Manage an infinite number of infinity bottles. 
    fontawesome_icon_name                 : th-list
    
  - title                                 : Free Tracking
    description                           : Track every addition and pour. View current bottle volume and proof. For free.
    fontawesome_icon_name                 : magic

  - title                                 : Rating & Notes
    description                           : Rate your pours and add tasting notes to track your bottle's unique flavor profile over time.
    fontawesome_icon_name                 : star
    
  - title                                 : Spirit Manager
    description                           : Maintain a personal database of spirits to reuse later so you can spend less time tapping and more time sipping.  View spirit usage across all of your bottles and additions. 
    fontawesome_icon_name                 : tasks
    
  - title                                 : Premium Tracking
    description                           : Purchase premium tracking to view detailed contents and details of every pour. 
    fontawesome_icon_name                 : chart-pie
    
  - title                                 : Cloud Sync
    description                           : View and manage your bottles from any iOS device using iCloud. No new accounts, signups, or logins. 
    fontawesome_icon_name                 : cloud

  - title                                 : Native
    description                           : Designed from the ground up for iOS to ensure your spend less time tracking and more time enjoying your pours.  
    fontawesome_icon_name                 : flask



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#d17a00"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#d17a00"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#d17a00"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#d17a00"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
